<?php

namespace andyp\webcomponent_hero\acf;

class acf_panel
{
    public function __construct()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_5fe851833a553',
                'title' => 'WebComponent : Hero - Anime.js',
                'fields' => array(
                    array(
                        'key' => 'field_5fe852c5b41dc',
                        'label' => '<span class="mdi mdi-bacteria-outline"></span> Instance',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5fe851834662c',
                        'label' => 'Slug',
                        'name' => 'wc_hero_slug',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5fe8518346694',
                        'label' => '<span class="mdi mdi-package-variant"></span> Container',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5fe85183466d8',
                        'label' => '',
                        'name' => 'wc_hero_container_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5fe85183543aa',
                                'label' => '<span class="mdi mdi-lifebuoy"></span> Float',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe85183543f1',
                                'label' => 'Float CSS',
                                'name' => 'wc_hero_container_float_css',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => 'display: block;
            width: 100%;
            height: 812px;
            float: left;',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe8518354432',
                                'label' => '<span class="mdi mdi-grid"></span> Grid',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe851835449b',
                                'label' => 'Enabled',
                                'name' => 'wc_hero_container_grid_enabled',
                                'type' => 'true_false',
                                'instructions' => 'Only works if "@supports (display: grid) {"',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5fe8518354505',
                                'label' => 'Grid CSS Rules',
                                'name' => 'wc_hero_container_grid_css',
                                'type' => 'textarea',
                                'instructions' => 'Rules only. No classes of moustache brackets.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe8518354546',
                                'label' => '<span class="mdi mdi-tablet-ipad"></span> Tablet',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe85183545af',
                                'label' => 'Enabled',
                                'name' => 'wc_hero_container_tablet_enabled',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5fe8518354617',
                                'label' => 'Breakpoint',
                                'name' => 'wc_hero_container_tablet_breakpoint',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '1024px',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5fe8518354680',
                                'label' => 'Float CSS Rules',
                                'name' => 'wc_hero_container_tablet_float_css',
                                'type' => 'textarea',
                                'instructions' => 'Rules only. No classes/IDs',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183546c2',
                                'label' => 'Grid CSS Rules',
                                'name' => 'wc_hero_container_tablet_grid_css',
                                'type' => 'textarea',
                                'instructions' => 'Rules only. No classes/IDs',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe851835472c',
                                'label' => '<span class="mdi mdi-cellphone-iphone"></span> Mobile',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe8518354795',
                                'label' => 'Enabled',
                                'name' => 'wc_hero_container_mobile_enabled',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183547d7',
                                'label' => 'Breakpoint',
                                'name' => 'wc_hero_container_mobile_breakpoint',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '768px',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5fe851835483f',
                                'label' => 'Float CSS Rules',
                                'name' => 'wc_hero_container_mobile_float_css',
                                'type' => 'textarea',
                                'instructions' => 'Rules only. No classes/IDs',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183548a8',
                                'label' => 'Grid CSS Rules',
                                'name' => 'wc_hero_container_mobile_grid_css',
                                'type' => 'textarea',
                                'instructions' => 'Rules only. No classes/IDs',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183548ea',
                                'label' => '<span class="mdi mdi-language-css3"></span> CSS',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe8518354951',
                                'label' => 'CSS',
                                'name' => 'wc_hero_container_css',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183549bb',
                                'label' => '<span class="mdi mdi-language-javascript"></span> JS',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_5fe8518354a7b',
                                'label' => 'JS',
                                'name' => 'wc_hero_container_js',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => 'ue__codemirror',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 10,
                                'new_lines' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5fe85183abae8',
                        'label' => '<span class="mdi mdi-view-carousel-outline"></span> Panels',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5fe85183b3c9e',
                        'label' => 'Panel Instance',
                        'name' => 'wc_hero_panel_instance',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'hide_admin' => 0,
                        'collapsed' => 'field_5fe85183b7be0',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5fe85183b7be0',
                                'label' => 'Panel Name',
                                'name' => 'wc_hero_panel_slug',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183b7c23',
                                'label' => 'Classes',
                                'name' => 'wc_hero_panel_classes',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5fe85183b7c61',
                                'label' => '',
                                'name' => 'wc_hero_panel_group',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'hide_admin' => 0,
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5fe85183c3f53',
                                        'label' => '<span class="mdi mdi-image"></span> Image',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c3f99',
                                        'label' => 'Image',
                                        'name' => 'wc_hero_panel_image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'return_format' => 'id',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c3fd9',
                                        'label' => 'Image Type',
                                        'name' => 'wc_hero_panel_image_type',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'choices' => array(
                                            'background' => 'background-image:url()',
                                            'img' => '<IMG>',
                                        ),
                                        'default_value' => array(
                                            0 => 'background',
                                        ),
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'value',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4018',
                                        'label' => 'Image Lazyload',
                                        'name' => 'wc_hero_panel_image_lazyload',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 1,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4056',
                                        'label' => 'Image CSS',
                                        'name' => 'wc_hero_panel_image_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4095',
                                        'label' => '<span class="mdi mdi-text-box"></span> Content',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c40d4',
                                        'label' => 'Content Pre HTML',
                                        'name' => 'wc_hero_panel_content_pre_html',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4113',
                                        'label' => 'Content HTML',
                                        'name' => 'wc_hero_panel_content_html',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4151',
                                        'label' => 'Content CSS',
                                        'name' => 'wc_hero_panel_content_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4190',
                                        'label' => '<span class="mdi mdi-lifebuoy"></span> Float',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c41ce',
                                        'label' => 'Float CSS',
                                        'name' => 'wc_hero_panel_float_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c425c',
                                        'label' => '<span class="mdi mdi-grid"></span> Grid',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c429d',
                                        'label' => 'Enabled',
                                        'name' => 'wc_hero_panel_grid_enabled',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 1,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c42dc',
                                        'label' => 'Grid CSS',
                                        'name' => 'wc_hero_panel_grid_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4345',
                                        'label' => '<span class="mdi mdi-tablet-ipad"></span> Tablet',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c43ae',
                                        'label' => 'Enabled',
                                        'name' => 'wc_hero_panel_tablet_enabled',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 1,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c43f0',
                                        'label' => 'Breakpoint',
                                        'name' => 'wc_hero_panel_tablet_breakpoint',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '1024px',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c4459',
                                        'label' => 'Float CSS',
                                        'name' => 'wc_hero_panel_tablet_float_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c44c2',
                                        'label' => 'Grid CSS',
                                        'name' => 'wc_hero_panel_tablet_grid_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c452b',
                                        'label' => '<span class="mdi mdi-cellphone-iphone"></span> Mobile',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c456c',
                                        'label' => 'Enabled',
                                        'name' => 'wc_hero_panel_mobile_enabled',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 1,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c45d4',
                                        'label' => 'Breakpoint',
                                        'name' => 'wc_hero_panel_mobile_breakpoint',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '768px',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c463d',
                                        'label' => 'Float CSS',
                                        'name' => 'wc_hero_panel_mobile_float_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c467e',
                                        'label' => 'Grid CSS',
                                        'name' => 'wc_hero_panel_mobile_grid_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c46e6',
                                        'label' => '<span class="mdi mdi-language-css3"></span> CSS',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c474f',
                                        'label' => 'CSS',
                                        'name' => 'wc_hero_panel_css',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c47b8',
                                        'label' => '<span class="mdi mdi-language-javascript"></span> JS',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5fe85183c47f9',
                                        'label' => 'JS',
                                        'name' => 'wc_hero_panel_js',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'ue__codemirror',
                                            'id' => '',
                                        ),
                                        'hide_admin' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 10,
                                        'new_lines' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'componentshortcodes',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => false,
                'description' => '',
            ));
            
            endif;
    }
}

